// Document model. Stores rich-text content as HTML generated by the
// TipTap editor, which preserves formatting (bold, italic, headings, lists)
// without needing a separate structure field.

import mongoose, { Schema, models, model } from "mongoose";

export interface IDocument {
  _id: mongoose.Types.ObjectId;
  title: string;
  content: string; // HTML from TipTap
  owner: mongoose.Types.ObjectId;
  sharedWith: mongoose.Types.ObjectId[]; // users granted edit access
  createdAt: Date;
  updatedAt: Date;
}

const DocumentSchema = new Schema<IDocument>(
  {
    title: { type: String, required: true, default: "Untitled Document" },
    content: { type: String, default: "" },
    owner: { type: Schema.Types.ObjectId, ref: "User", required: true },
    sharedWith: [{ type: Schema.Types.ObjectId, ref: "User" }],
  },
  { timestamps: true }
);

export default models.Document || model<IDocument>("Document", DocumentSchema);